language: haxe

os:
  - linux
  - osx

dist: trusty

haxe:
  - "3.4.7"
  - "4.0.0-preview.3"
  - development

matrix:
  allow_failures:
    - haxe: development

hxml:
  - server.hxml
  - web.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    branch: master
    haxe: "3.4.7"
    condition: $TRAVIS_OS_NAME = linux
  skip_cleanup: true
